#!/bin/bash

#PBS -N ocn_averages
#PBS -q regular
#PBS -l select=4:ncpus=4:mpiprocs=4
#PBS -l walltime=01:00:00
#PBS -A None


##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########


today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/glade/u/home/asalazar/cesm2/cesm_caseroot/b.e21.B1850.f19_g17.8xCO2_nostrato_PaleoCalibr.001/postprocess/logs/ocn_averages.log.$today

module load ncarenv/23.09
module load intel
module load intel-mpi/2021.10.0
module load apptainer


mpirun singularity run -B /glade,/var /glade/work/bdobbins/Containers/CESM_Postprocessing/image /opt/ncar/cesm_postprocessing/cesm-env2/bin/ocn_avg_generator.py  --caseroot /glade/u/home/asalazar/cesm2/cesm_caseroot/b.e21.B1850.f19_g17.8xCO2_nostrato_PaleoCalibr.001/postprocess >> ${log_filename} 2>&1 

